# Generated by Django 2.1.2 on 2018-10-31 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blog_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
