# Generated by Django 2.1.2 on 2018-11-01 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0003_auto_20181031_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
